### ISSUE TITLE
Memory leak while training with custom data

### ISSUE THREAD

**Issue by WoodwindHu** [DNMP/DNMP#12]
Memory leak while training DNMP on my own data (with 1920x1080 images). 
The memory usage keeps increasing over time.
![企业微信截图_2bc69143-6cca-4fac-9f90-b3936df65892](https://github.com/DNMP/DNMP/assets/28439907/c5ce26c3-756a-49d7-b5dc-e7321329dc6c)
<img width="1438" alt="image" src="https://github.com/DNMP/DNMP/assets/28439907/e1eabb76-6237-4433-a43f-be00b2aa636a">

**Comment by FanLu97** [comment]
Hi, the problem may be related to the cache mechanism when training the rendering. We store rasterization results of certain poses in memory and re-use the results next time (for faster training). You may disable the cache mechanism by using `--use_rasterizer_cache False` if your memory is not enough (which may lead to low training speed due to that we rasterize full-resolution image for each training step).

**Comment by WoodwindHu** [comment]
Thank you, it worked!
