### ISSUE TITLE
How to edit the Scene?

### ISSUE THREAD

**Issue by WoodwindHu** [DNMP/DNMP#9]

**Comment by FanLu97** [comment]
We have tried: texture editing, object insertion/delection.
For texture editing, we first paint a single image and then finetune the model on the image (only finetune radiance features).
For object insertion, we manually repeat/delect the DNMPs of the object (can be done using Blender).
Due to that the editing process involves many manual operations, we will not include this part in this repository. Sorry for the inconvenience.

**Comment by huangqiusheng** [comment]
great work! I am curious about the operation of removing static background vehicles, as demonstrated in the paper. How do you complete the ground color information? (Since the network does not have access to this information due to occlusion by static vehicles)
